"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import {
    saveProduct,
    deleteProduct,
    toggleProductStatus as toggleStatusDb,
    updateOrderStatus as updateOrderStatusDb,
    getProduct
} from "./db";
import { Product } from "./types";

// Helper to parse FormData to Product
function parseProductFormData(formData: FormData): Omit<Product, 'id' | 'createdAt' | 'updatedAt' | 'isActive'> {
    const name = formData.get("name") as string;
    const description = formData.get("description") as string;
    const price = parseFloat(formData.get("price") as string);
    const category = formData.get("category") as string;
    const stock = parseInt(formData.get("stock") as string);
    const size = formData.get("size") as string;
    const imageUrl = formData.get("imageUrl") as string;
    const imagesStr = formData.get("images") as string;
    const images = imagesStr ? JSON.parse(imagesStr) : [];

    return {
        name,
        description,
        price,
        category,
        stock,
        size,
        imageUrl,
        images
    };
}

export async function addProduct(formData: FormData) {
    const productData = parseProductFormData(formData);

    await saveProduct({
        ...productData,
        isActive: true, // Default to active
        // id will be generated by backend if missing
    } as Product);

    revalidatePath("/admin/products");
    revalidatePath("/shop");
    revalidatePath("/");
    redirect("/admin/products");
}

export async function editProduct(id: string, formData: FormData) {
    const productData = parseProductFormData(formData);

    // We need to keep the existing isActive status and createdAt
    const existingProduct = await getProduct(id);

    await saveProduct({
        id, // Ensure ID is passed
        ...productData,
        isActive: existingProduct?.isActive ?? true,
        createdAt: existingProduct?.createdAt,
    } as Product);

    revalidatePath("/admin/products");
    revalidatePath(`/admin/products/${id}`);
    revalidatePath("/shop");
    revalidatePath(`/product/${id}`);
    redirect("/admin/products");
}

export async function removeProduct(id: string) {
    await deleteProduct(id);
    revalidatePath("/admin/products");
    revalidatePath("/shop");
}

export async function toggleProductStatus(id: string) {
    await toggleStatusDb(id);
    revalidatePath("/admin/products");
    revalidatePath("/shop");
}

export async function updateOrderStatus(orderId: string, status: string, logisticsId?: string) {
    await updateOrderStatusDb(orderId, status as any, logisticsId);
    revalidatePath("/admin/orders");
    revalidatePath(`/order/${orderId}`);
    return { success: true };
}

export async function addDiscount(formData: FormData) {
    // Placeholder
}

export async function removeDiscount(id: string) {
    // Placeholder
}
